import { formatDigest } from "../src/digest/formatter.js";
import type { DigestReport } from "../src/digest/analyzer.js";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const date = new Date("2025-06-15T12:00:00Z");

function makeFullReport(): DigestReport {
  return {
    ciFailures: [
      {
        repo: "user/alpha",
        workflowName: "CI",
        url: "https://github.com/user/alpha/actions/runs/1",
        failedAt: "2025-06-15T11:30:00Z",
      },
    ],
    prsAwaitingReview: [
      {
        number: 1,
        title: "Add feature X",
        state: "open",
        user: "alice",
        html_url: "https://github.com/user/alpha/pull/1",
        updated_at: "2025-06-15T12:00:00Z",
        draft: false,
        review_decision: null,
        repoName: "user/alpha",
      },
    ],
    newIssues: [
      {
        number: 10,
        title: "Bug report",
        state: "open",
        user: "carol",
        html_url: "https://github.com/user/alpha/issues/10",
        created_at: "2025-06-15T12:00:00Z",
        labels: ["bug"],
        repoName: "user/alpha",
      },
    ],
    activitySummary: {
      reposWithActivity: 2,
      totalWorkflowRuns: 5,
      totalPRs: 3,
      totalIssues: 2,
    },
    reposWithoutCI: ["user/beta"],
  };
}

function makeEmptyReport(): DigestReport {
  return {
    ciFailures: [],
    prsAwaitingReview: [],
    newIssues: [],
    activitySummary: {
      reposWithActivity: 0,
      totalWorkflowRuns: 0,
      totalPRs: 0,
      totalIssues: 0,
    },
    reposWithoutCI: [],
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("formatDigest", () => {
  it("contains the date header", () => {
    const output = formatDigest(makeFullReport(), date);
    expect(output).toContain("# Daily Digest: 2025-06-15");
  });

  it("renders CI failures with repo names and links", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("## CI Failures");
    expect(output).toContain("user/alpha");
    expect(output).toContain("CI");
    expect(output).toContain("[View](https://github.com/user/alpha/actions/runs/1)");
    expect(output).toContain("2025-06-15 11:30:00");
  });

  it("renders PRs section with titles and authors", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("## PRs Awaiting Review");
    expect(output).toContain("#1 Add feature X");
    expect(output).toContain("@alice");
    expect(output).toContain("https://github.com/user/alpha/pull/1");
  });

  it("renders new issues section correctly", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("## New Issues");
    expect(output).toContain("#10 Bug report");
    expect(output).toContain("https://github.com/user/alpha/issues/10");
  });

  it("activity summary has correct numbers", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("**Repos with activity**: 2");
    expect(output).toContain("**Total workflow runs**: 5");
    expect(output).toContain("**Total PRs**: 3");
    expect(output).toContain("**Total issues**: 2");
  });

  it("renders repos without CI", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("## Repos Without CI");
    expect(output).toContain("- user/beta");
  });

  it("shows 'None' for empty sections", () => {
    const output = formatDigest(makeEmptyReport(), date);

    // Each empty section should show "None"
    const noneCount = (output.match(/^None$/gm) || []).length;
    // CI Failures, PRs Awaiting Review, New Issues, Repos Without CI = 4 sections
    expect(noneCount).toBe(4);
  });

  it("footer contains the copilot link", () => {
    const output = formatDigest(makeFullReport(), date);

    expect(output).toContain("https://github.com/anombyte93/copilot");
    expect(output).toContain("Generated by");
  });
});
