import type { DigestReport } from "./analyzer.js";

function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

export function formatDigest(report: DigestReport, date: Date): string {
  const dateStr = formatDate(date);
  const lines: string[] = [];

  // Header
  lines.push(`# Daily Digest: ${dateStr}`);
  lines.push("");

  // CI Failures
  lines.push("## CI Failures");
  lines.push("");
  if (report.ciFailures.length === 0) {
    lines.push("None");
  } else {
    lines.push("| Repo | Workflow | Failed At | Link |");
    lines.push("|------|----------|-----------|------|");
    for (const f of report.ciFailures) {
      const failedDate = f.failedAt.slice(0, 19).replace("T", " ");
      lines.push(
        `| ${f.repo} | ${f.workflowName} | ${failedDate} | [View](${f.url}) |`,
      );
    }
  }
  lines.push("");

  // PRs Awaiting Review
  lines.push("## PRs Awaiting Review");
  lines.push("");
  if (report.prsAwaitingReview.length === 0) {
    lines.push("None");
  } else {
    for (const pr of report.prsAwaitingReview) {
      lines.push(
        `- **${pr.repoName ?? "unknown"}** — [#${pr.number} ${pr.title}](${pr.html_url}) by @${pr.user}`,
      );
    }
  }
  lines.push("");

  // New Issues
  lines.push("## New Issues");
  lines.push("");
  if (report.newIssues.length === 0) {
    lines.push("None");
  } else {
    for (const issue of report.newIssues) {
      lines.push(
        `- **${issue.repoName ?? "unknown"}** — [#${issue.number} ${issue.title}](${issue.html_url})`,
      );
    }
  }
  lines.push("");

  // Activity Summary
  lines.push("## Activity Summary");
  lines.push("");
  const s = report.activitySummary;
  lines.push(`- **Repos with activity**: ${s.reposWithActivity}`);
  lines.push(`- **Total workflow runs**: ${s.totalWorkflowRuns}`);
  lines.push(`- **Total PRs**: ${s.totalPRs}`);
  lines.push(`- **Total issues**: ${s.totalIssues}`);
  lines.push("");

  // Repos Without CI
  lines.push("## Repos Without CI");
  lines.push("");
  if (report.reposWithoutCI.length === 0) {
    lines.push("None");
  } else {
    for (const repo of report.reposWithoutCI) {
      lines.push(`- ${repo}`);
    }
  }
  lines.push("");

  // Footer
  lines.push("---");
  lines.push(
    "*Generated by [copilot](https://github.com/anombyte93/copilot)*",
  );
  lines.push("");

  return lines.join("\n");
}
